// Exportas cada componente individualmente
export { default as Button } from './Button.astro';
export { default as HeadingSection } from './HeadingSection.astro';
export { default as MainContainer } from './MainContainer.astro';
export { default as Carousel } from './Carousel.astro';
export { default as Badge } from './Badge.astro';
export { default as Logotipo } from './Logotipo.astro';
export { default as HeroCarousel } from './HeroCarousel.astro';
export { default as Icon } from './Icon.astro';
export { default as ServiceCard } from './ServiceCard.astro';
export { default as ProjectCard } from './ProjectCard.astro';
export { default as TestimonialCard } from './TestimonialCard.astro';
export { default as StatCounter } from './StatCounter.astro';
export { default as ContactForm } from './ContactForm.astro';
export { default as FaqAccordion } from './FaqAccordion.astro';
export { default as FeatureList } from './FeatureList.astro';
export { default as HeroPage } from './HeroPage.astro';
export { default as BlogCard } from './BlogCard.astro';
export { default as Breadcrumbs } from './Breadcrumbs.astro';